In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [4]:
sales_df = pd.read_csv('./data/advertising.csv')

In [11]:
sales_df[0:5]

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [10]:
sales_df = sales_df.drop("Unnamed:0",axis = 1)

KeyError: "['Unnamed:0'] not found in axis"

In [12]:
sales_df.shape

(200, 4)

In [14]:
sales_df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

## Set X and Y variables

In [16]:
Y = sales_df.Sales
X = pd.DataFrame(sales_df.TV)

# Split Data Set

In [17]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test, \
y_train,y_test = train_test_split(X,Y,train_size = 0.8,random_state = 100)

In [24]:
X_train.shape

(160, 1)

In [25]:
X_test.shape

(40, 1)

In [28]:
X_train[0:5]

TV
168  215.4
112  175.7
171  164.5
181  218.5
7    120.2

# Build Model

Linear Regression

In [29]:
from sklearn.linear_model import LinearRegression

In [33]:
lreg_vl = LinearRegression()

In [36]:
lreg_vl.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [38]:
lreg_vl.intercept_

7.113008222196275

In [40]:
lreg_vl.coef_

array([0.04610976])

In [42]:
y_pred_v1 = lreg_vl.predict(X_test)

In [44]:
y_df_v1 = pd.DataFrame ({"actual":y_test,
                        "predicted":y_pred_v1,
                        "residual":y_test - y_pred_v1})

In [45]:
y_df_v1[5:10]

actual  predicted  residual
167    12.2  16.648506 -4.448506
116    12.2  13.531486 -1.331486
96     11.7  16.224296 -4.524296
52     22.6  17.091160  5.508840
69     22.3  17.109603  5.190397

## Metrics : MSE

In [46]:
from sklearn.metrics import mean_squared_error

In [47]:
mse_v1= mean_squared_error(y_df_v1.actual,
                          y_df_v1.predicted) 

In [ ]:
import numpy as np
np.sqrt(mse_v1)

#Y + 2.Rmse

# Rsquare

In [50]:
lreg_vl.score(X_train,y_train)

0.6197569503198974

In [51]:
from sklearn.metrics import r2_score

In [53]:
r2_score(y_df_v1.actual,
        y_df_v1.predicted)

0.5441581483697225

In [54]:
### Multiple Linear Regression

In [66]:
y = sales_df.Sales
X = pd.DataFrame(sales_df[['TV','Radio','Newspaper']])

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_Train,X_Test, \
y_Train,y_test = train_test_split(X,y,train_size = 0.2)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


# Build Model

In [69]:
from sklearn.linear_model import LinearRegression

In [70]:
lr = LinearRegression()

In [81]:
lr.fit(X_Train,y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [82]:
lr.intercept_

3.3108981995040274

In [84]:
lr.coef_

array([ 0.0450529 ,  0.19510582, -0.00809727])

In [86]:
y_pred = lr.predict(X_Test)

In [87]:
mse = mean_squared_error(y_test,y_pred)
mse

3.1239290617179685

In [88]:
np.sqrt(mse)

1.7674640199217546

In [91]:
r2_score(y_test,y_pred)

0.8862998295050442

# Add an interacyion variable

In [93]:
X['tv_radio'] = X['TV'] * X['Radio']

In [128]:
X_Train,X_Test, \
y_Train,y_Test = train_test_split(X,y,train_size = 0.2)

In [98]:
lr.fit(X_Train,y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [100]:
y_pred = lr.predict(X_Test)

In [102]:
y_pred = lr.predict(X_Test)

In [104]:
mse = mean_squared_error(y_test,y_pred)
mse

1.0714605131659987

In [106]:
np.sqrt(mse)

1.03511376822357

In [107]:
r2_score(y_test,y_pred)

0.9583014227922331

# KNN Algorithm

In [110]:
from sklearn.neighbors import KNeighborsRegressor

In [114]:
knn_v4 = KNeighborsRegressor(n_neighbors = 5)

In [129]:
knn_v4.fit(X_Train,y_Train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [118]:

from sklearn.model_selection import cross_val_score

In [130]:
knn_scores = cross_val_score(KNeighborsRegressor(n_neighbors = 5),
                            X_train,
                            y_train,
                            cv = 5,
                            scoring = 'r2')

In [133]:
knn_scores

array([0.5393304 , 0.09664232, 0.21160596, 0.55656922, 0.73200283])

In [134]:
knn_predict = knn_v4.predict(X_Test)

In [124]:
mean_sq = mean_squared_error?

In [135]:
mean_sq = mean_squared_error(y_test,knn_predict)

In [137]:
np.sqrt(mean_sq)

6.814351032930428

# Grid Search

In [138]:
params = {"n_neighbors":[4,6,8,10],
           "weights":['uniform','distance']}

In [139]:
from sklearn.model_selection import GridSearchCV

In [140]:
knn_grid = GridSearchCV(KNeighborsRegressor(),
                       param_grid = params,
                       cv = 5,
                       scoring = 'r2')

In [141]:
knn_grid.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [4, 6, 8, 10], 'weights': ['uniform', 'distance']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)

In [142]:
knn_grid.cv_results_

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\de

{'mean_fit_time': array([0.00291195, 0.00280843, 0.00180235, 0.00180058, 0.00399413,
        0.0033505 , 0.00266013, 0.00341458]),
 'std_fit_time': array([1.49174870e-03, 2.32397967e-03, 2.23074838e-03, 1.83454406e-03,
        1.56414218e-06, 1.69067413e-03, 1.52071186e-03, 1.76928227e-03]),
 'mean_score_time': array([0.00100651, 0.00120821, 0.00275588, 0.00321932, 0.00159745,
        0.00393038, 0.00400014, 0.00535831]),
 'std_score_time': array([0.00156303, 0.00160284, 0.0016254 , 0.00161036, 0.00195647,
        0.00265688, 0.00108344, 0.00270468]),
 'param_n_neighbors': masked_array(data=[4, 4, 6, 6, 8, 8, 10, 10],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value

In [144]:
knn_grid.best_params_

{'n_neighbors': 10, 'weights': 'uniform'}

In [146]:
knn_grid.best_score_

0.5009094991109528

In [148]:
cv_results = knn_grid.cv_results_

In [152]:
grid_results_df = pd.DataFrame( { 'models' : cv_results['params'],
                                'mean_score' : cv_results['mean_test_score'],
                                'std_score': cv_results['std_test_score'] })

In [153]:
grid_results_df

models  mean_score  std_score
0    {'n_neighbors': 4, 'weights': 'uniform'}    0.379957   0.262678
1   {'n_neighbors': 4, 'weights': 'distance'}    0.229150   0.356920
2    {'n_neighbors': 6, 'weights': 'uniform'}    0.429453   0.241044
3   {'n_neighbors': 6, 'weights': 'distance'}    0.269927   0.338160
4    {'n_neighbors': 8, 'weights': 'uniform'}    0.483877   0.231554
5   {'n_neighbors': 8, 'weights': 'distance'}    0.300725   0.323496
6   {'n_neighbors': 10, 'weights': 'uniform'}    0.500909   0.211807
7  {'n_neighbors': 10, 'weights': 'distance'}    0.317844   0.309476

# Deploying


In [155]:
from sklearn.externals import joblib

In [156]:
joblib.dump(knn_v4,"sales.model")

['sales.model']